#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Expand projects.html (RU/EN/UZ):
  1. add 4 new planet nodes (labels idx 4-7 + detail cards)
  2. add a full categorized reference-list section (all ~20 projects)
  3. timeline: company founded 2016, project experience since 2010
Idempotent: guards on data-idx="4" and id="reference-list".
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

# new flagship planet nodes (idx 4-7). Images are AI-generated by the client;
# onerror falls back to an existing asset so nothing breaks before upload.
NEW_NODES = [
    {  # idx 4
        'img': 'project-water-samarkand.jpg', 'num': '05',
        'ru': {'cat': 'Водоснабжение', 'name': 'Водоснабжение (Самарканд)',
               'title': 'Водоснабжение Самаркандской области',
               'desc': 'Строительство систем водоснабжения и водозаборных сооружений для населённых пунктов Самаркандской области по ICB-контрактам стандарта АБР.',
               'cl': 'Заказчик:', 'clv': 'Suv-Taraqqiyot LLC', 'il': 'Институт:', 'ilv': 'Азиатский Банк Развития (АБР)', 'badge': 'FIDIC / ICB'},
        'en': {'cat': 'Water Supply', 'name': 'Water Supply (Samarkand)',
               'title': 'Water Supply, Samarkand Region',
               'desc': 'Construction of water supply systems and water intake facilities for settlements across the Samarkand Region under ADB-financed ICB contracts.',
               'cl': 'Client:', 'clv': 'Suv-Taraqqiyot LLC', 'il': 'Institution:', 'ilv': 'Asian Development Bank (ADB)', 'badge': 'FIDIC / ICB'},
        'uz': {'cat': 'Suv ta\'minoti', 'name': 'Suv ta\'minoti (Samarqand)',
               'title': 'Samarqand viloyati suv ta\'minoti',
               'desc': 'Samarqand viloyati aholi punktlari uchun suv ta\'minoti tizimlari va suv olish inshootlarini ADB ICB shartnomalari bo\'yicha qurish.',
               'cl': 'Buyurtmachi:', 'clv': 'Suv-Taraqqiyot LLC', 'il': 'Institut:', 'ilv': 'Osiyo Taraqqiyot Banki (ADB)', 'badge': 'FIDIC / ICB'},
    },
    {  # idx 5
        'img': 'project-a380-carec.jpg', 'num': '06',
        'ru': {'cat': 'Транспортный коридор', 'name': 'Автодорога А-380 (ЦАРЭС 2)',
               'title': 'Автодорога А-380 (ЦАРЭС 2)',
               'desc': 'Реконструкция автодороги А-380 Ташкент–Бухара–Нукус–Бейнеу (транспортный коридор ЦАРЭС 2) при финансировании АБР — один из первых коридорных проектов, с 2010 года.',
               'cl': 'Заказчик:', 'clv': 'POSCO Engineering · GP Papenburg', 'il': 'Институт:', 'ilv': 'Азиатский Банк Развития (АБР)', 'badge': 'FIDIC MDB Harmonised'},
        'en': {'cat': 'Transport Corridor', 'name': 'A-380 Highway (CAREC 2)',
               'title': 'A-380 Highway (CAREC 2)',
               'desc': 'Reconstruction of the A-380 Tashkent–Bukhara–Nukus–Beyneu highway (CAREC Corridor 2), financed by ADB — one of our earliest corridor assignments, from 2010.',
               'cl': 'Client:', 'clv': 'POSCO Engineering · GP Papenburg', 'il': 'Institution:', 'ilv': 'Asian Development Bank (ADB)', 'badge': 'FIDIC MDB Harmonised'},
        'uz': {'cat': 'Transport yo\'lagi', 'name': 'A-380 avtoyo\'li (CAREC 2)',
               'title': 'A-380 avtoyo\'li (CAREC 2)',
               'desc': 'A-380 Toshkent–Buxoro–Nukus–Beyneu avtomobil yo\'lini rekonstruksiya qilish (CAREC 2 yo\'lagi), ADB tomonidan moliyalashtirilgan — 2010 yildan boshlangan loyihalardan biri.',
               'cl': 'Buyurtmachi:', 'clv': 'POSCO Engineering · GP Papenburg', 'il': 'Institut:', 'ilv': 'Osiyo Taraqqiyot Banki (ADB)', 'badge': 'FIDIC MDB Harmonised'},
    },
    {  # idx 6
        'img': 'project-smart-nurafshon.jpg', 'num': '07',
        'ru': {'cat': 'Цифровая инфраструктура', 'name': 'Smart City Нурафшон',
               'title': 'Smart City Нурафшон',
               'desc': 'Развитие инфраструктуры «умного города» Нурафшон по модели EPC: интеграция городской инженерии и цифровых систем.',
               'cl': 'Заказчик:', 'clv': 'АО Evrascon', 'il': 'Модель:', 'ilv': 'EPC', 'badge': 'EPC'},
        'en': {'cat': 'Smart City', 'name': 'Smart City Nurafshon',
               'title': 'Smart City Nurafshon',
               'desc': 'Development of smart-city infrastructure in Nurafshon under an EPC model: integration of urban engineering and digital systems.',
               'cl': 'Client:', 'clv': 'Evrascon JSC', 'il': 'Model:', 'ilv': 'EPC', 'badge': 'EPC'},
        'uz': {'cat': 'Raqamli infratuzilma', 'name': 'Smart City Nurafshon',
               'title': 'Smart City Nurafshon',
               'desc': 'Nurafshon «aqlli shahar» infratuzilmasini EPC modeli bo\'yicha rivojlantirish: shahar muhandisligi va raqamli tizimlarni integratsiya qilish.',
               'cl': 'Buyurtmachi:', 'clv': 'Evrascon AJ', 'il': 'Model:', 'ilv': 'EPC', 'badge': 'EPC'},
    },
    {  # idx 7
        'img': 'project-energy-metering.jpg', 'num': '08',
        'ru': {'cat': 'Энергетика', 'name': 'Энергоучёт (АБР)',
               'title': 'Автоматизированный учёт электроэнергии',
               'desc': 'Внедрение автоматизированной системы мониторинга и учёта электроэнергии для потребителей Бухарской, Джизакской и Самаркандской областей.',
               'cl': 'Заказчик:', 'clv': 'KT-Corporation (Корея)', 'il': 'Институт:', 'ilv': 'Азиатский Банк Развития (АБР)', 'badge': 'ADB'},
        'en': {'cat': 'Energy', 'name': 'Smart Metering (ADB)',
               'title': 'Automated Electricity Metering',
               'desc': 'Implementation of an automated electricity monitoring and metering system for consumers across the Bukhara, Jizzakh and Samarkand regions.',
               'cl': 'Client:', 'clv': 'KT-Corporation (Korea)', 'il': 'Institution:', 'ilv': 'Asian Development Bank (ADB)', 'badge': 'ADB'},
        'uz': {'cat': 'Energetika', 'name': 'Energiya hisobi (ADB)',
               'title': 'Avtomatlashtirilgan elektr hisobi',
               'desc': 'Buxoro, Jizzax va Samarqand viloyatlari iste\'molchilari uchun elektr energiyasini monitoring qilish va hisobga olishning avtomatlashtirilgan tizimini joriy etish.',
               'cl': 'Buyurtmachi:', 'clv': 'KT-Corporation (Koreya)', 'il': 'Institut:', 'ilv': 'Osiyo Taraqqiyot Banki (ADB)', 'badge': 'ADB'},
    },
]

# full reference list, grouped. meta strings are language-neutral enough to reuse;
# only the project name + category title are translated.
REF = {
    'ru': {
        'eyebrow': 'Полный референс-лист',
        'heading': 'Более 20 реализованных проектов',
        'intro': 'Компания Bridge Consult основана в 2016 году. Наши специалисты сопровождают инфраструктурные проекты по проформам контрактов FIDIC и при участии международных финансовых институтов с 2010 года.',
        'founded': 'год основания', 'since': 'опыт проектов с', 'count': 'проектов',
        'cats': [
            ('Дороги и транспортные коридоры', [
                ('Реконструкция автодороги М39, км 1295–1315 (Лот 3)', '2025–2026 · NEW TECH SAMARKAND · FIDIC'),
                ('Реконструкция 54 км сельских дорог, Бухарская обл. (4174-UZB)', '2025–2026 · NEW TECH SAMARKAND · FIDIC'),
                ('SRRP: реконструкция 107 км (4R105 и 4R100)', '2024–2025 · Lankaran Yul Tikinti · FIDIC Red Book (АБР)'),
                ('Региональные и сельские дороги, Ташкентская обл., Фаза 2', '2023–2024 · Lankaran Yul Tikinti · Red Book MDB (АБР)'),
                ('А-373 Ташкент–Ош, перевал Камчик (ЦАРЭС 2), 58 км', '2013–2022 · Evrascon · Corsan-Corviam · FIDIC MDB'),
                ('А-380 Ташкент–Бухара–Нукус–Бейнеу (ЦАРЭС 2), км 440–490', '2011–2013 · GP Papenburg · АБР'),
                ('А-380 (ЦАРЭС 2), км 490–581', '2010–2011 · POSCO Engineering · АБР'),
            ]),
            ('Водоснабжение и санитария', [
                ('Водоснабжение и водозаборы, Самаркандская обл. (KWSP/4.1)', '2023–2024 · Suv-Taraqqiyot · АБР'),
                ('Водоснабжение и водозаборы, Самаркандская обл. (KWSP/3.1)', '2016–2022 · Suv-Taraqqiyot · АБР'),
                ('Водоснабжение севера г. Намангана, 60 км (NWSP/4.2)', '2023–2024 · Suv-Taraqqiyot · OPEC Fund'),
                ('Системы водоснабжения, г. Янгиюль', '2023–2024 · Suv-Taraqqiyot · World Bank'),
                ('Реконструкция водозабора «Джийдакапа»', '2023–2024 · Suv-Taraqqiyot · EBRD · Yellow Book'),
            ]),
            ('Спорт, город и Smart City', [
                ('Олимпийский городок — спортивные объекты (IV Азиатские игры)', '2022–2025 · Минстрой РУз · EPC+F'),
                ('Smart City Нурафшон', '2017 · Evrascon · EPC'),
            ]),
            ('Энергетика и нефтегаз', [
                ('Автоматизированный учёт электроэнергии (Бухара, Джизак, Самарканд)', '2017 · KT-Corporation · АБР'),
                ('Кандымский газоперерабатывающий комплекс (СРП Узбекистан–Lukoil)', '2005–2006 · СРП'),
                ('Ферганский НПЗ — толлинговый контракт', '2008–2010 · Umidli Hamkor'),
            ]),
            ('Институциональное развитие и арбитраж', [
                ('Городские дороги Ташкента — контракт EPC+F (FIDIC Yellow Book)', '2025–2026 · Tashkent Invest Company'),
                ('TA-6697 REG — поддержка готовности проектов, Центр. и Зап. Азия', '2025–2026 · АБР · Армения'),
                ('Арбитраж ICC — спор по дорожному контракту на $23 млн (выигран)', 'FIDIC Subcontract · 2010 Edition'),
            ]),
        ],
    },
    'en': {
        'eyebrow': 'Complete Reference List',
        'heading': 'Over 20 Delivered Projects',
        'intro': 'Bridge Consult was founded in 2016. Our specialists have been advising infrastructure projects under FIDIC forms of contract and with international financial institutions since 2010.',
        'founded': 'founded', 'since': 'project experience since', 'count': 'projects',
        'cats': [
            ('Roads & Transport Corridors', [
                ('M39 highway reconstruction, km 1295–1315 (Lot 3)', '2025–2026 · NEW TECH SAMARKAND · FIDIC'),
                ('Reconstruction of 54 km rural roads, Bukhara Region (4174-UZB)', '2025–2026 · NEW TECH SAMARKAND · FIDIC'),
                ('SRRP: reconstruction of 107 km (4R105 & 4R100)', '2024–2025 · Lankaran Yul Tikinti · FIDIC Red Book (ADB)'),
                ('Regional & rural roads, Tashkent Region, Phase 2', '2023–2024 · Lankaran Yul Tikinti · Red Book MDB (ADB)'),
                ('A-373 Tashkent–Osh, Kamchik Pass (CAREC 2), 58 km', '2013–2022 · Evrascon · Corsan-Corviam · FIDIC MDB'),
                ('A-380 Tashkent–Bukhara–Nukus–Beyneu (CAREC 2), km 440–490', '2011–2013 · GP Papenburg · ADB'),
                ('A-380 (CAREC 2), km 490–581', '2010–2011 · POSCO Engineering · ADB'),
            ]),
            ('Water Supply & Sanitation', [
                ('Water supply & intakes, Samarkand Region (KWSP/4.1)', '2023–2024 · Suv-Taraqqiyot · ADB'),
                ('Water supply & intakes, Samarkand Region (KWSP/3.1)', '2016–2022 · Suv-Taraqqiyot · ADB'),
                ('Northern Namangan water supply, 60 km (NWSP/4.2)', '2023–2024 · Suv-Taraqqiyot · OPEC Fund'),
                ('Water supply systems, Yangiyul City', '2023–2024 · Suv-Taraqqiyot · World Bank'),
                ('Jiydakapa water intake reconstruction', '2023–2024 · Suv-Taraqqiyot · EBRD · Yellow Book'),
            ]),
            ('Sports, Urban & Smart City', [
                ('Olympic City — sports facilities (IV Asian Youth Games)', '2022–2025 · Min. of Construction · EPC+F'),
                ('Smart City Nurafshon', '2017 · Evrascon · EPC'),
            ]),
            ('Energy & Oil/Gas', [
                ('Automated electricity metering (Bukhara, Jizzakh, Samarkand)', '2017 · KT-Corporation · ADB'),
                ('Kandym Gas Processing Complex (PSA Uzbekistan–Lukoil)', '2005–2006 · PSA'),
                ('Fergana Refinery — tolling contract', '2008–2010 · Umidli Hamkor'),
            ]),
            ('Institutional Development & Arbitration', [
                ('Tashkent urban roads — EPC+F contract (FIDIC Yellow Book)', '2025–2026 · Tashkent Invest Company'),
                ('TA-6697 REG — project readiness support, Central & West Asia', '2025–2026 · ADB · Armenia'),
                ('ICC arbitration — USD 23M road contract dispute (won)', 'FIDIC Subcontract · 2010 Edition'),
            ]),
        ],
    },
    'uz': {
        'eyebrow': 'To\'liq referens-ro\'yxat',
        'heading': '20 dan ortiq amalga oshirilgan loyiha',
        'intro': 'Bridge Consult kompaniyasi 2016 yilda tashkil etilgan. Mutaxassislarimiz 2010 yildan beri FIDIC shartnoma proformalarini qo\'llab va xalqaro moliya institutlari ishtirokida infratuzilma loyihalarini olib boradi.',
        'founded': 'tashkil etilgan', 'since': 'loyiha tajribasi', 'count': 'loyiha',
        'cats': [
            ('Yo\'llar va transport yo\'laklari', [
                ('M39 avtoyo\'li rekonstruksiyasi, km 1295–1315 (Lot 3)', '2025–2026 · NEW TECH SAMARKAND · FIDIC'),
                ('54 km qishloq yo\'llari rekonstruksiyasi, Buxoro vil. (4174-UZB)', '2025–2026 · NEW TECH SAMARKAND · FIDIC'),
                ('SRRP: 107 km rekonstruksiyasi (4R105 va 4R100)', '2024–2025 · Lankaran Yul Tikinti · FIDIC Red Book (ADB)'),
                ('Mintaqaviy va qishloq yo\'llari, Toshkent vil., 2-bosqich', '2023–2024 · Lankaran Yul Tikinti · Red Book MDB (ADB)'),
                ('A-373 Toshkent–O\'sh, Qamchiq dovoni (CAREC 2), 58 km', '2013–2022 · Evrascon · Corsan-Corviam · FIDIC MDB'),
                ('A-380 Toshkent–Buxoro–Nukus–Beyneu (CAREC 2), km 440–490', '2011–2013 · GP Papenburg · ADB'),
                ('A-380 (CAREC 2), km 490–581', '2010–2011 · POSCO Engineering · ADB'),
            ]),
            ('Suv ta\'minoti va sanitariya', [
                ('Suv ta\'minoti va suv olish inshootlari, Samarqand vil. (KWSP/4.1)', '2023–2024 · Suv-Taraqqiyot · ADB'),
                ('Suv ta\'minoti va suv olish inshootlari, Samarqand vil. (KWSP/3.1)', '2016–2022 · Suv-Taraqqiyot · ADB'),
                ('Namangan shimoli suv ta\'minoti, 60 km (NWSP/4.2)', '2023–2024 · Suv-Taraqqiyot · OPEC Fund'),
                ('Suv ta\'minoti tizimlari, Yangiyo\'l sh.', '2023–2024 · Suv-Taraqqiyot · World Bank'),
                ('«Jiydakapa» suv olish inshooti rekonstruksiyasi', '2023–2024 · Suv-Taraqqiyot · EBRD · Yellow Book'),
            ]),
            ('Sport, shahar va Smart City', [
                ('Olimpiya shaharchasi — sport inshootlari (IV Osiyo o\'yinlari)', '2022–2025 · Qurilish vazirligi · EPC+F'),
                ('Smart City Nurafshon', '2017 · Evrascon · EPC'),
            ]),
            ('Energetika va neft-gaz', [
                ('Avtomatlashtirilgan elektr hisobi (Buxoro, Jizzax, Samarqand)', '2017 · KT-Corporation · ADB'),
                ('Qandim gazni qayta ishlash kompleksi (MUB Oʻzbekiston–Lukoil)', '2005–2006 · MUB'),
                ('Farg\'ona NQZ — tolling shartnomasi', '2008–2010 · Umidli Hamkor'),
            ]),
            ('Institutsional rivojlanish va arbitraj', [
                ('Toshkent shahar yo\'llari — EPC+F shartnoma (FIDIC Yellow Book)', '2025–2026 · Tashkent Invest Company'),
                ('TA-6697 REG — loyiha tayyorligini qo\'llab-quvvatlash, Markaziy va G\'arbiy Osiyo', '2025–2026 · ADB · Armaniston'),
                ('ICC arbitraji — $23 mln yo\'l shartnomasi bo\'yicha nizo (yutilgan)', 'FIDIC Subcontract · 2010 Edition'),
            ]),
        ],
    },
}

FILES = {
    'public/projects.html': ('ru', ''),
    'public/EN/projects.html': ('en', '../'),
    'public/UZ/projects.html': ('uz', '../'),
}

LABELS_ANCHOR = '    </div>\n\n    <div class="uni-head"><div class="uni-head-inner">'
CARDS_ANCHOR = '        </article></div>\n        </div>\n    </div>\n</div>\n\n<!-- ============ PDF / COMPANY PROFILE CTA ============ -->'
REF_ANCHOR = '</div><!-- /uni-scene -->'


def esc(s):
    return s.replace('&', '&amp;').replace('"', '&quot;')


def build_labels(lang, P):
    out = []
    for i, n in enumerate(NEW_NODES):
        idx = i + 4
        d = n[lang]
        alt = esc(d['title'] + ' — Bridge Consult')
        out.append(
            '        <button class="uni-label" type="button" data-idx="%d"><img class="uni-thumb" src="%s%s" alt="%s" loading="lazy" onerror="this.onerror=null;this.src=\'%snews-cover.jpg\'"><span class="uni-label-txt"><span class="uni-num">%s</span><span class="uni-cat">%s</span><span class="uni-name">%s</span></span></button>'
            % (idx, P, n['img'], alt, P, n['num'], esc(d['cat']), esc(d['name'])))
    return '\n'.join(out)


def build_cards(lang, P):
    out = []
    for i, n in enumerate(NEW_NODES):
        idx = i + 4
        d = n[lang]
        alt = esc(d['title'])
        reverse = (idx % 2 == 1)
        flexdir = 'lg:flex-row-reverse' if reverse else 'lg:flex-row'
        chap = ('-right-10 md:-right-20 font-sans text-right w-full' if reverse
                else '-left-10 md:-left-20 font-sans hidden md:block')
        out.append('''            <div class="uni-detail-card" data-idx="%d" hidden><article class="flex flex-col %s items-center gap-10 md:gap-16 mb-24 relative">
            <div class="chapter-number %s">%s</div>
            <div class="lg:w-1/2 w-full relative z-10 group">
                <div class="aspect-video w-full bg-gray-200 rounded-3xl overflow-hidden premium-shadow relative">
                    <div class="absolute inset-0 bg-bridge-dark/10 group-hover:bg-transparent transition-colors z-10"></div>
                    <img src="%s%s" alt="%s" loading="lazy" onerror="this.onerror=null;this.src='%snews-cover.jpg'" class="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-700 group-hover:scale-105">
                    <div class="absolute top-6 left-6 z-20 flex gap-2">
                        <span class="bg-bridge-dark text-white text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider shadow-lg">%s</span>
                    </div>
                </div>
            </div>
            <div class="lg:w-1/2 w-full relative z-10">
                <span class="text-bridge-taupe font-bold tracking-widest uppercase text-xs mb-3 block">%s</span>
                <h2 class="text-3xl md:text-4xl font-bold text-bridge-dark mb-4">%s</h2>
                <p class="text-gray-600 font-light text-lg mb-6">%s</p>
                <div class="bg-gray-50 border border-gray-100 rounded-2xl p-5 space-y-3 inline-block w-full md:w-auto">
                    <p class="text-bridge-dark font-medium"><span class="text-gray-400 font-bold text-xs uppercase tracking-widest mr-3">%s</span> %s</p>
                    <p class="text-bridge-dark font-medium"><span class="text-gray-400 font-bold text-xs uppercase tracking-widest mr-3">%s</span> %s</p>
                </div>
            </div>
        </article></div>''' % (idx, flexdir, chap, n['num'], P, n['img'], alt, P,
                               esc(d['badge']), esc(d['cat']), esc(d['title']), esc(d['desc']),
                               esc(d['cl']), esc(d['clv']), esc(d['il']), esc(d['ilv'])))
    return '\n'.join(out)


def build_ref(lang):
    r = REF[lang]
    nn = 0
    cats_html = []
    for cat_title, projects in r['cats']:
        rows = []
        for name, meta in projects:
            nn += 1
            rows.append('''              <div class="group flex gap-4 items-start rounded-2xl border border-white/10 bg-white/[0.03] p-5 hover:border-bridge-taupe/50 hover:bg-white/[0.06] transition-all duration-300">
                <span class="text-bridge-taupe font-bold text-xs mt-1 shrink-0">%02d</span>
                <div>
                  <h4 class="text-white font-semibold leading-snug mb-1.5">%s</h4>
                  <p class="text-gray-500 text-xs font-medium tracking-wide">%s</p>
                </div>
              </div>''' % (nn, esc(name), esc(meta)))
        cats_html.append('''          <div data-aos="fade-up">
            <div class="flex items-center gap-4 mb-6">
              <h3 class="text-lg md:text-xl font-bold text-white whitespace-nowrap">%s</h3>
              <span class="h-px flex-grow bg-white/10"></span>
              <span class="text-xs font-bold text-bridge-taupe shrink-0">%d</span>
            </div>
            <div class="grid md:grid-cols-2 gap-4">
%s
            </div>
          </div>''' % (esc(cat_title), len(projects), '\n'.join(rows)))

    return '''
<!-- ============ FULL REFERENCE LIST ============ -->
<section id="reference-list" class="relative overflow-hidden font-sans py-20 md:py-28" style="background:#14120f; color:#fff;">
    <div class="absolute top-0 left-1/2 -translate-x-1/2 w-[700px] h-[360px] rounded-full pointer-events-none" style="background:rgba(138,123,102,0.10); filter:blur(120px);"></div>
    <div class="max-w-6xl mx-auto px-6 relative z-10">
        <div class="text-center max-w-3xl mx-auto mb-16" data-aos="fade-up">
            <div class="inline-flex items-center gap-3 mb-5 text-bridge-taupe font-bold uppercase tracking-[0.28em] text-[11px]"><span class="w-8 h-px bg-bridge-taupe"></span>%s<span class="w-8 h-px bg-bridge-taupe"></span></div>
            <h2 class="text-3xl md:text-5xl font-bold leading-tight mb-5" style="color:#fff;">%s</h2>
            <p class="text-gray-400 font-light leading-relaxed">%s</p>
            <div class="inline-flex items-center gap-5 md:gap-7 mt-8">
              <span class="text-center"><span class="text-2xl md:text-3xl font-bold text-white block leading-none mb-1">2016</span><span class="text-[10px] font-bold uppercase tracking-widest text-bridge-taupe">%s</span></span>
              <span class="w-px h-9 bg-white/15"></span>
              <span class="text-center"><span class="text-2xl md:text-3xl font-bold text-white block leading-none mb-1">2010</span><span class="text-[10px] font-bold uppercase tracking-widest text-bridge-taupe">%s</span></span>
              <span class="w-px h-9 bg-white/15"></span>
              <span class="text-center"><span class="text-2xl md:text-3xl font-bold text-white block leading-none mb-1">20+</span><span class="text-[10px] font-bold uppercase tracking-widest text-bridge-taupe">%s</span></span>
            </div>
        </div>
        <div class="space-y-12">
%s
        </div>
    </div>
</section>
''' % (esc(r['eyebrow']), esc(r['heading']), esc(r['intro']),
       esc(r['founded']), esc(r['since']), esc(r['count']), '\n'.join(cats_html))


for path, (lang, P) in FILES.items():
    print('=== %s (%s) ===' % (path, lang))
    with open(path, 'r', encoding='utf-8') as f:
        c = f.read()

    if 'data-idx="4"' in c:
        print('  nodes already present — skip labels/cards')
    else:
        assert LABELS_ANCHOR in c, 'labels anchor not found in ' + path
        assert CARDS_ANCHOR in c, 'cards anchor not found in ' + path
        c = c.replace(LABELS_ANCHOR, build_labels(lang, P) + '\n' + LABELS_ANCHOR, 1)
        c = c.replace(CARDS_ANCHOR, build_cards(lang, P) + '\n' + CARDS_ANCHOR, 1)
        print('  + 4 labels, + 4 detail cards')

    if 'id="reference-list"' in c:
        print('  reference list already present — skip')
    else:
        assert REF_ANCHOR in c, 'ref anchor not found in ' + path
        c = c.replace(REF_ANCHOR, REF_ANCHOR + build_ref(lang), 1)
        print('  + reference-list section')

    with open(path, 'w', encoding='utf-8') as f:
        f.write(c)
    print('  saved')

print('\nDone.')
